import { Main } from "next/document";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
	AiFillTwitterCircle,
	AiFillLinkedin,
	AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import ayan from "../public/assets/hi.png";
import project1 from "../public/assets/ZenFoci.png";
import project2 from "../public/assets/TheFootWorks.png";
import back from "../public/assets/back.png";
import filmFlix from "../public/assets/FilmFlix.png";
import reactPortfolio1 from "../public/assets/React-Portfolio1.png";
import Hero from "../components/Hero";
import About from "../components/About";
import Projects from "../components/Projects";

function index() {
	return (
		<div>
			<Head>
				<title>Ayan Ahmed Portfolio</title>
				<meta name="description" content="Generated by cre" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* <Hero />
			<About />
			<Projects /> */}
		</div>
	);
}

export default index;
